export const CHANGE_CATEGOERY ="CHANGE_CATEGOERY";
export const CHANGE_DIFFICULT ="CHANGE_DIFFICULT";
export const CHANGE_TYPE ="CHANGE_TYPE";
export const CHANGE_AMOUNT ="CHANGE_AMOUNT";
export const CHANGE_SCORE ="CHANGE_SCORE";